name: Pylint and Deploy to EC2

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11.9"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
    
  deploy:
    runs-on: ubuntu-latest
    needs: build  # depends on the job named build
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup SSH
      run: |
        mkdir ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
      # chown ubuntu:ubuntu ~/.ssh
      # chown ubuntu:ubuntu ~/.ssh/id_rsa
        
    - name: SSH into server and setup environment
      run: |
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@${{ secrets.EC2_IP }}
        sudo apt update
        sudo apt upgrade
        sudo apt install python3

    - name: Clone, setup env, and run.
      run: |
        cd /opt
        git clone https://github.com/zakjanzi/streamlit-recipe-app.git
        cd streamlit-recipe-app && python3 -m venv stramlit_env
        source streamlit_env/bin/activate
        streamlit_env/pip install requirements
        streamlit_env/bin/streamlit run app.py

      

# Questions:
# 1. Should I include the pip installation in the job or is it available by default in Github's CI server?
# 2. How are permissions managed in this EC2 instance you gave us? Got an error when using sudo mkdir
# 3. What about the users? Got an error when I ran  `chown ubuntu:ubuntu` to the .ssh folder i created in the previous step but got this error: invalid user: ‘ubuntu:ubuntu’

